(def name "Emerald")
(def text "Grants [Emerald].")
(def type (starting artifact))
(def cost (list (mana 1)))
(def cast cast-permanent)
(def enters-field '(add-gem caster emerald 1))
(def leaves-field '(add-gem caster emerald -1))
