(def name "Infused Onyx")
(def text "Grants [Onyx].")
(def type (starting artifact))
(def cost (list (life 3)))
(def cast cast-permanent)
(def enters-field '(add-gem caster onyx 1))
(def leaves-field '(add-gem caster onyx -1))
