(def name "Infused Sapphire")
(def text "Grants [Sapphire].")
(def type (starting artifact))
(def cost (list (life 3)))
(def cast cast-permanent)
(def enters-field '(add-gem caster sapphire 1))
(def leaves-field '(add-gem caster sapphire -1))
