(def name "Infused Jade")
(def text "Grants [Jade].")
(def type (starting artifact))
(def cost (list (life 3)))
(def cast cast-permanent)
(def enters-field '(add-gem caster jade 1))
(def leaves-field '(add-gem caster jade -1))
