(def name "Infused Topaz")
(def text "Grants [Topaz].")
(def type (starting artifact))
(def cost (list (life 3)))
(def cast cast-permanent)
(def enters-field '(add-gem caster topaz 1))
(def leaves-field '(add-gem caster topaz -1))
