(def name "Onyx")
(def text "Grants [Onyx].")
(def type (starting artifact))
(def cost (list (mana 1)))
(def cast cast-permanent)
(def enters-field '(add-gem caster onyx 1))
(def leaves-field '(add-gem caster onyx -1))
