(def name "Opal")
(def text "Grants [Opal].")
(def type (starting artifact))
(def cost (list (mana 1)))
(def cast cast-permanent)
(def enters-field '(add-gem caster opal 1))
(def leaves-field '(add-gem caster opal -1))
