(def name "Scum Dredger")
(def text "When Scum Dredger comes into play or dies, put the top two cards of your library into your discard pile.")
(def type (starting creature))
(def cost (list (mana 1) (gem sapphire)))
(def stats (pair 1 1))
(def cast cast-permanent)
