(def name "Suppression Novice")
(def text "When Suppression Novice comes into play, the next nonartifact card played before your next turn costs (1) more.")
(def type (starting creature))
(def cost (list (mana 1) (gem pearl)))
(def stats (pair 1 1))
(def cast cast-permanent)
