(def name "Worldy Savant")
(def text "Grants 1 Emerald as long as you have 3 or more creatures.")
(def type (starting creature))
(def cost (list (mana 2) (gem emerald 1)))
(def stats (pair 2 2))
(def cast cast-permanent)
